# Generated by Django 4.1 on 2022-08-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shirt_size',
            new_name='Quality',
        ),
    ]
